language: python
python: "2.7"

install:
  - sudo apt-get update
  - pip install ansible

before_script:
  - sudo mkdir -p /var/www/default

script:
  - ansible-playbook -i inventory/travis.ini test.yml --connection=local --sudo
  - php -v
  - sudo php5-fpm -t

# ex: et sw=2 ts=2:
