---
- name: Test | Install and configure PHP.
  hosts: all
  sudo: yes
  vars_files:
    - 'defaults/main.yml'
  vars:
    php_packages_extra:
      - mongodb
    php_pecl_packages:
      - timezonedb
      - mongo
  tasks:
    - include: 'tasks/main.yml'
  handlers:
    - include: 'handlers/main.yml'

# ex: filetype=ansible et ts=2 sw=2:

