---
- name: All available roles _o7
  hosts: all
  sudo: yes
  vars_files:
    - 'defaults/main.yml'
  tasks:
    - include: 'tasks/main.yml'
  handlers:
    - include: 'handlers/main.yml'

# ex: filetype=ansible et ts=2 sw=2:

