---
- name: Debian | Include role variables.
  include_vars: "Debian.yml"

- name: Debian | Define current distribution and required PHP version.
  set_fact: hwr_path_debian_version_variables="Debian_{{ ansible_lsb.codename }}_php{{ hwr_options.php_version }}.yml"
  when: hwr_options.php_version is defined

- name: Dabian | Include LSB and PHP version variables
  include_vars: "{{ hwr_path_debian_version_variables }}"
  when: hwr_path_debian_version_variables is defined

- name: Debian | Compile PHP packages to install
  set_fact: php_packages="{{ hwr_default_php_packages + hwr_php_fpm_packages + php_packages_extra | list }}"
  when: php_packages is not defined

- name: Debian | Import GPG keys for custom repositories
  apt_key: >
    url="{{ item.url }}"
    state="{{ item.state }}"
  with_items: hwr_apt_keys
  when:
    - hwr_apt_keys is defined

- name: Debian | Enable APT repositories
  apt_repository: >
    repo="{{ item.repo }}"
    state="{{ item.state }}"
    update_cache=yes
  with_items: hwr_apt_repositories
  when:
    - hwr_apt_repositories is defined

- name: Debian | Installation
  apt: >
    name={{ item }}
    state=installed
    default_release="{{ hwr_apt_default_release }}"
    update_cache=yes
    cache_valid_time=300
  with_items: php_packages

# ex: ft=ansible et sw=2 ts=2:
