# tasks/fpm.yml
#
# Manage FPM pools and configuration.
---

- name: FPM | php-fpm.conf configuration.
  template: >
    src="fpm.conf.j2"
    dest="{{ hwr_path_php_fpm_conf }}"
    backup=yes

- name: FPM | Remove default pool.
  file: >
    path="{{ hwr_path_php_fpm_pools }}/www.conf"
    state="absent"
  notify:
    - Restart PHP-FPM

- name: FPM | Create pools.
  template: >
    src=fpm-pool.conf.j2
    dest="{{ hwr_path_php_fpm_pools }}/{{ item.name }}.conf"
    backup=yes
  with_items: hwr_fpm_pools
  notify:
    - Restart PHP-FPM

- name: FPM | Enable service on boot.
  service: >
    name="{{ hwr_service_php_fpm }}"
    state="started"
    enabled="yes"

# ex: ft=ansible et sw=2 ts=2:
