---
- name: Include default role variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define packages to install
  set_fact: php_packages="{{ hwr_default_php_packages + hwr_php_fpm_packages | list }}"
  when: php_packages is not defined

- name: Enable LTS (Debian-squeeze)
  apt_repository: >
    repo='deb http://http.debian.net/debian/ squeeze-lts main contrib non-free'
    state=present
  when: ansible_lsb.codename == 'squeeze'

- name: Installation (Debian-family)
  apt: >
    name={{ item }}
    state=installed
    update_cache=yes
  with_items: php_packages
  when: ansible_os_family == "Debian"

- name: Compile desired php.ini
  set_fact: php_ini="{{ hwr_config_php_ini + php_ini }}"

- name: CLI's php.ini configuration
  ini_file: >
    dest="{{ hwr_path_php_ini_cli }}"
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items: php_ini

- name: FPM's php.ini configuration
  ini_file: >
    dest="{{ hwr_path_php_ini_fpm }}"
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items: php_ini
  when: hwr_options.enable_fpm

- name: FPM configuration
  template: >
    src="fpm.conf.j2"
    dest="{{ hwr_path_php_fpm_conf }}"
    backup=yes
  when: hwr_options.enable_fpm

- name: Remove default pool
  file: >
    path="{{ hwr_path_php_fpm_pools }}/www.conf"
    state="absent"
  when: hwr_options.enable_fpm
  notify:
    - Restart PHP-FPM

- name: Create FPM pools
  template: >
    src=fpm-pool.conf.j2
    dest="{{ hwr_path_php_fpm_pools }}/{{ item.name }}.conf"
    backup=yes
  with_items: hwr_fpm_pools
  when: hwr_options.enable_fpm
  notify:
    - Restart PHP-FPM

- name: Enable PHP-FPM service
  service: >
    name="{{ hwr_service_php_fpm }}"
    state="started"
    enabled="yes"
  when: hwr_options.enable_fpm

# ex: ft=ansible et sw=2 ts=2:
