---
php_ini:
  # Use this in your playbooks to define your desired configuration
  - section: "PHP"
    option: "display_errors"
    value: "On"

hwr_config_php_ini:
  - section: "PHP"
    option: "short_open_tag"
    value: "On"
  - section: "PHP"
    option: "precision"
    value: 14
  - section: "PHP"
    option: "output_buffering"
    value: 4096
  - section: "PHP"
    option: "expose_php"
    value: "On"
  - section: "PHP"
    option: "max_execution_time"
    value: 30
  - section: "PHP"
    option: "max_input_time"
    value: 60
  - section: "PHP"
    option: "memory_limit"
    value: "128M"
  - section: "PHP"
    option: "error_reporting"
    value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
  - section: "PHP"
    option: "display_errors"
    value: "On"
  - section: "PHP"
    option: "log_errors"
    value: "On"
  - section: "PHP"
    option: "error_log"
    value: ""
  - section: "PHP"
    option: "post_max_size"
    value: "8M"
  - section: "PHP"
    option: "default_mimetype"
    value: "text/html"
  - section: "PHP"
    option: "default_charset"
    value: "UTF-8"
  - section: "PHP"
    option: "file_uploads"
    value: "On"
  - section: "PHP"
    option: "upload_max_filesize"
    value: "2M"
  - section: "PHP"
    option: "max_file_uploads"
    value: 20
  - section: "PHP"
    option: "allow_url_fopen"
    value: "On"
  - section: "PHP"
    option: "allow_url_include"
    value: "Off"
  - section: "PHP"
    option: "default_socket_timeout"
    value: 60
  - section: "Date"
    option: "date.timezone"
    value: "UTC"
  - section: "mail function"
    option: "sendmail_path"
    value: "sendmail -t -i"
  - section: "Session"
    option: "session.save_handler"
    value: "file"
  - section: "Session"
    option: "session.save_path"
    value: "/var/lib/php5"
  - section: "Session"
    option: "session.use_cookies"
    value: "On"
  - section: "Session"
    option: "session.cookie_secure"
    value: ""
  - section: "Session"
    option: "session.use_only_cookies"
    value: "On"
  - section: "Session"
    option: "session.name"
    value: "PHPSESSID"
  - section: "Session"
    option: "session.auto_start"
    value: "Off"
  - section: "Session"
    option: "session.cookie_httponly"
    value: ""
  - section: "Session"
    option: "session.serialize_handler"
    value: "php"




# ex: filetype=ansible et ts=2 sw=2:
