---
- name: Include default role variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define packages to install
  set_fact: php_packages="{{ hwr_default_php_packages | list }}"
  when: php_packages is not defined

- name: Enable LTS (Debian-squeeze)
  apt_repository: >
    repo='deb http://http.debian.net/debian/ squeeze-lts main contrib non-free'
    state=present
  when: ansible_lsb.codename == 'squeeze'

- name: Installation (Debian-family)
  apt: >
    name={{ item }}
    state=installed
    update_cache=yes
  with_items: php_packages
  when: ansible_os_family == "Debian"

- name: Compile desired php.ini
  set_fact: php_ini="{{ hwr_config_php_ini + php_ini }}"

- name: Configuration
  ini_file: >
    dest="{{ hwr_path_php_ini_cli }}"
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
  with_items: php_ini

# ex: ft=ansible et sw=2 ts=2:

