---
hwr_default_php_packages:
  - php5
  - php5-cli
  - php5-common
  - php5-curl
  - php5-fpm
  - php5-gd
  - php5-intl
  - php5-mcrypt
  - php5-mysqlnd
  - php5-sqlite
  - php5-xsl
  # Useful for development
  - php5-dbg
  - php5-dev
  - php5-xdebug

# ex: filetype=ansible et sw=2 ts=2:
